apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
        labels:
          app: polybot
    spec:
      containers:
      - name: server
        image: 352708296901.dkr.ecr.eu-north-1.amazonaws.com/alonit-polybot-prod:0.0.6
---
apiVersion: v1
kind: Service
metadata:
  name: polybot-svc
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443